apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenactorservice
  labels:
    app: kitchenactorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchenactorservice
  template:
    metadata:
      labels:
        app: kitchenactorservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "kitchenactorservice"
        dapr.io/app-port: "80"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: kitchenactorservice
        image: daprsamples.azurecr.io/daprdinner/kitchenactorservice:24816
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dinnersecret
        
